### 查询服务实例信息
GET http://127.0.0.1:8000/ecommerce-nacos-client/nacos-client/service-instance
Accept: application/json

### 动态从 Nacos Server 中获取配置信息
GET http://127.0.0.1:8000/ecommerce-nacos-client/nacos-client/project-config
Accept: application/json

### 查看 Sleuth 跟踪信息
GET http://127.0.0.1:9001/asan/ecommerce-nacos-client/sleuth/trace-info
Accept: application/json
e-commerce-user: eyJhbGciOiJSUzI1NiJ9.eyJlLWNvbW1lcmNlLXVzZXIiOiJ7XCJpZFwiOjEwLFwidXNlcm5hbWVcIjpcImFzYW4xMjNAcXEuY29tXCJ9IiwianRpIjoiM2YxMTIzMWYtMzdhZC00NTk5LWE4YTUtMjZjYjU0NWQxMjYxIiwiZXhwIjoxNjQyMzQ4ODAwfQ.jKuHGrO_Ghj2rWMOf3S-WYfY_cRWG5JjUKmsVz-JViG-zdYc-KPgOv8XK4FQJxVhswB6KnSeozk1oJ7zzZ5JsaQcSW2Xj6HWTqQsWHchlevm_ehAggjE1vnKV_Ys50jvNMyY2f_SDmVsZBd6TXVfk1lcyUZIcJt40dOaD1mc1nuSQoNrTteTje-V4MYjQ-zapNYu_LOhD-exfjJrLz4meDF0PlF6CNf2bSsGsjWt_60sm_ZiAcjbOQD_CR0N_lHVT_G-kzlATjCsGxDveZiBhGUpXIbtJ1NO9qJGHT9-2MJCVl91VZK21N_6JbiTiWaEaD-Hgi0ACICA1akc8IGsZg
token: asan

###
