### 获取 Token
POST http://127.0.0.1:9001/asan/ecommerce-nacos-client/communication/token-by-feign
Content-Type: application/json
e-commerce-user: eyJhbGciOiJSUzI1NiJ9.eyJlLWNvbW1lcmNlLXVzZXIiOiJ7XCJpZFwiOjEwLFwidXNlcm5hbWVcIjpcImFzYW4xMjNAcXEuY29tXCJ9IiwianRpIjoiNGM0OTM2ZDUtNWQ4MC00MGI2LTgwNzktOWVhZjU5ODJlYTBlIiwiZXhwIjoxNjQzMTI2NDAwfQ.Mfytj0HSOULgaErID5WaleYsMFczX3yI3dR463GNivBb3Hvvyy_Qu6y-yM-yJ6Chwno7c_iZEDYT57SDgOsB519Dk1LSodu9-BpIqa32bZDoFQ2daGxAMw_47SNEhpG5RbD14uOum2FV1DRsDwv4qkYP3PYNpyowCRPy4FzU3yrYG8RzgAgZKyiH__GSE1AzbJy70rC4NOag-UWsy_Qos-G_N55pApOf1GfXMtrDLQLzrRM7rEPY5qIr8nUp060ip7QOh8P6EXhXr9ziSsTBE_bGUsRASzBZpghPjNUepAHRTY6W1H6ty5UYDCfSWv_MKe1t_weotQ4-QpjyggE2Bg
token: asan

{
  "username": "asan123@qq.com",
  "password": "25d55ad283aa400af464c76d713c07ad"
}


### 根据提供的 serviceId 获取实例信息
GET http://127.0.0.1:9001/asan/ecommerce-nacos-client/hystrix/hystrix-command-annotation?serviceId=e-commerce-nacos-client
Content-Type: application/json
e-commerce-user: eyJhbGciOiJSUzI1NiJ9.eyJlLWNvbW1lcmNlLXVzZXIiOiJ7XCJpZFwiOjEwLFwidXNlcm5hbWVcIjpcImFzYW4xMjNAcXEuY29tXCJ9IiwianRpIjoiNGM0OTM2ZDUtNWQ4MC00MGI2LTgwNzktOWVhZjU5ODJlYTBlIiwiZXhwIjoxNjQzMTI2NDAwfQ.Mfytj0HSOULgaErID5WaleYsMFczX3yI3dR463GNivBb3Hvvyy_Qu6y-yM-yJ6Chwno7c_iZEDYT57SDgOsB519Dk1LSodu9-BpIqa32bZDoFQ2daGxAMw_47SNEhpG5RbD14uOum2FV1DRsDwv4qkYP3PYNpyowCRPy4FzU3yrYG8RzgAgZKyiH__GSE1AzbJy70rC4NOag-UWsy_Qos-G_N55pApOf1GfXMtrDLQLzrRM7rEPY5qIr8nUp060ip7QOh8P6EXhXr9ziSsTBE_bGUsRASzBZpghPjNUepAHRTY6W1H6ty5UYDCfSWv_MKe1t_weotQ4-QpjyggE2Bg
token: asan


### 根据提供的 serviceId 获取实例信息
GET http://127.0.0.1:9001/asan/ecommerce-nacos-client/hystrix/simple-hystrix-command?serviceId=e-commerce-nacos-client
Content-Type: application/json
e-commerce-user: eyJhbGciOiJSUzI1NiJ9.eyJlLWNvbW1lcmNlLXVzZXIiOiJ7XCJpZFwiOjEwLFwidXNlcm5hbWVcIjpcImFzYW4xMjNAcXEuY29tXCJ9IiwianRpIjoiNGM0OTM2ZDUtNWQ4MC00MGI2LTgwNzktOWVhZjU5ODJlYTBlIiwiZXhwIjoxNjQzMTI2NDAwfQ.Mfytj0HSOULgaErID5WaleYsMFczX3yI3dR463GNivBb3Hvvyy_Qu6y-yM-yJ6Chwno7c_iZEDYT57SDgOsB519Dk1LSodu9-BpIqa32bZDoFQ2daGxAMw_47SNEhpG5RbD14uOum2FV1DRsDwv4qkYP3PYNpyowCRPy4FzU3yrYG8RzgAgZKyiH__GSE1AzbJy70rC4NOag-UWsy_Qos-G_N55pApOf1GfXMtrDLQLzrRM7rEPY5qIr8nUp060ip7QOh8P6EXhXr9ziSsTBE_bGUsRASzBZpghPjNUepAHRTY6W1H6ty5UYDCfSWv_MKe1t_weotQ4-QpjyggE2Bg
token: asan


### 根据提供的 serviceId 获取实例信息
GET http://127.0.0.1:9001/asan/ecommerce-nacos-client/hystrix/hystrix-observable-command?serviceId=e-commerce-nacos-client
Content-Type: application/json
e-commerce-user: eyJhbGciOiJSUzI1NiJ9.eyJlLWNvbW1lcmNlLXVzZXIiOiJ7XCJpZFwiOjEwLFwidXNlcm5hbWVcIjpcImFzYW4xMjNAcXEuY29tXCJ9IiwianRpIjoiNGM0OTM2ZDUtNWQ4MC00MGI2LTgwNzktOWVhZjU5ODJlYTBlIiwiZXhwIjoxNjQzMTI2NDAwfQ.Mfytj0HSOULgaErID5WaleYsMFczX3yI3dR463GNivBb3Hvvyy_Qu6y-yM-yJ6Chwno7c_iZEDYT57SDgOsB519Dk1LSodu9-BpIqa32bZDoFQ2daGxAMw_47SNEhpG5RbD14uOum2FV1DRsDwv4qkYP3PYNpyowCRPy4FzU3yrYG8RzgAgZKyiH__GSE1AzbJy70rC4NOag-UWsy_Qos-G_N55pApOf1GfXMtrDLQLzrRM7rEPY5qIr8nUp060ip7QOh8P6EXhXr9ziSsTBE_bGUsRASzBZpghPjNUepAHRTY6W1H6ty5UYDCfSWv_MKe1t_weotQ4-QpjyggE2Bg
token: asan
