### 登录
POST 127.0.0.1:9001/asan/e-commerce/login
Content-Type: application/json

{
  "username": "asan123@qq.com",
  "password": "25d55ad283aa400af464c76d713c07ad"
}

### 注册
POST 127.0.0.1:9001/asan/e-commerce/register
Content-Type: application/json

{
  "username": "asan1231@imooc.com",
  "password": "25d55ad283aa400af464c76d713c07ad"
}
