### 查询服务
GET http://127.0.0.1:9001/asan/ecommerce-nacos-client/nacos-client/service-instance?serviceId=e-commerce-gateway
Accept: application/json
e-commerce-user: eyJhbGciOiJSUzI1NiJ9.eyJlLWNvbW1lcmNlLXVzZXIiOiJ7XCJpZFwiOjEwLFwidXNlcm5hbWVcIjpcImFzYW4xMjNAcXEuY29tXCJ9IiwianRpIjoiN2Q5ODg5NDUtYjVmNC00ZmNiLTllMWYtNzNmYTRiODQzZDg2IiwiZXhwIjoxNjQ1Mjg2NDAwfQ.E4JFRGVO_Ov5B1kcIZEXLjrmQ251jQA648-6gJm0GDghMi97D7KljOotuUh4n8fZI5zmTfJhjAnmKDDJcxEb6m1v_jaQ6k_gKx5LJTgMKvSjtwqZfmUkcNAOoV6Di4zWtgkrmAOmXEkHVsVdPKKxmHtqjBQ8O83n_9ybTYFKrnpbpS4LEnBfBNLLecAWjpS6IZaGl2eLFcGDU3AsUyePJ9AaJZwjvlZpngzZupF2Ss27cqeIWFeF6-v-bY3pRddSUGHI6nVUHUz_hh4urzkbD2Jem2TYOTMGlPzxpKyVhu8-ZEGohbB9FjVuCgyb6Jem8j0vwoooyvgJ0yOumysK4Q
token: asan

###
