### 登录
POST http://127.0.0.1:9001/asan/e-commerce/login
Content-Type: application/json

{
  "username": "asan123@qq.com",
  "password": "25d55ad283aa400af464c76d713c07ad"
}

### 查询服务 Nginx -> Gatyeway -> MicroService
GET http://127.0.0.1:9001/asan/ecommerce-nacos-client/nacos-client/service-instance?serviceId=e-commerce-gateway
Accept: application/json
e-commerce-user: eyJhbGciOiJSUzI1NiJ9.eyJlLWNvbW1lcmNlLXVzZXIiOiJ7XCJpZFwiOjEwLFwidXNlcm5hbWVcIjpcImFzYW4xMjNAcXEuY29tXCJ9IiwianRpIjoiZGQ3NjVhZDgtZWRhNS00ZGU3LWEwMjItMmIxNTgwMDExYmZlIiwiZXhwIjoxNjQ1MzcyODAwfQ.FyxWqG4I5R1c0c7JgYmCYvDQNufPfrUggAJFXTO1Y-OQeFuEGIvJTfskP5yxxtNvmasRddcfvh_T_vgnGr5r_WMYDM1Tb8dSSb3KN6vO1j2-hML1xUifOUQHHtdS-1-OewPbPP6grihFCq32W3Lhmftr_JUceoYVBVQVMBcexS6KrD8jB9UcEAQw0oModTfJKpBbsfTDhCphOSqlOy_Z4BYZ2n_h8tUNV3RAdYeas1wgdJzg2U3ZFm4VnVtNNSx832oAIBw40XdixHSbCY2cjJ4-PUb4UqVSnYtu31RoueoKdRTO9wFJNWn5mPKPRUWzwZbzO4BYWQ1OlVLZhoAe4w
token: asan

### SpringBoot Admin
http://127.0.0.1/e-commerce-admin

###
