### 根据 TableId 查询详细商品信息
POST http://127.0.0.1:9001/asan/ecommerce-goods-service/goods/goods-info
Content-Type: application/json
e-commerce-user: eyJhbGciOiJSUzI1NiJ9.eyJlLWNvbW1lcmNlLXVzZXIiOiJ7XCJpZFwiOjEwLFwidXNlcm5hbWVcIjpcImFzYW4xMjNAcXEuY29tXCJ9IiwianRpIjoiMjE1OTMwOTUtZTZhMi00Yzc3LWE5ZmItOGY1NTE3Y2M2MGI4IiwiZXhwIjoxNjQyODY3MjAwfQ.hdgjAjx-IVPDKdRUmz7oJJE7Wi1TizsPVJ_oyAPBYvp6DN7_oTRFzDDGGIUA3pbotLf5VUTpJ2XR7lkEmEx_8Yz-u8v5Q9DKSMt-avLwRGE5y3TLQmMx4RnKjq33Z6hTEshxuFzbRY1tXK7lcfTuWknnfi6TDa8hTzZO3FkOIUgiRHsJwSC_1YRxpg8cmQiz-XLUKilhYoGu02SvAgoot9GBUlVPMNDUgwPnWr4VL9kpGsfDJpKV30pP-9sdujbgwOd1KsFdWtEJYV8nxre7Nq2c6udT0a9wrs_uD7ff1FfIfDAFJZqCJUgKMuQWjsy6fnTAbodvKprtnQDNjjO_0Q

{
  "ids": [
    {
      "id": 10
    },
    {
      "id": 11
    }
  ]
}


### 根据分页查询简单商品信息
GET http://127.0.0.1:9001/asan/ecommerce-goods-service/goods/page-simple-goods-info?page=2
Accept: application/json
e-commerce-user: eyJhbGciOiJSUzI1NiJ9.eyJlLWNvbW1lcmNlLXVzZXIiOiJ7XCJpZFwiOjEwLFwidXNlcm5hbWVcIjpcImFzYW4xMjNAcXEuY29tXCJ9IiwianRpIjoiMjE1OTMwOTUtZTZhMi00Yzc3LWE5ZmItOGY1NTE3Y2M2MGI4IiwiZXhwIjoxNjQyODY3MjAwfQ.hdgjAjx-IVPDKdRUmz7oJJE7Wi1TizsPVJ_oyAPBYvp6DN7_oTRFzDDGGIUA3pbotLf5VUTpJ2XR7lkEmEx_8Yz-u8v5Q9DKSMt-avLwRGE5y3TLQmMx4RnKjq33Z6hTEshxuFzbRY1tXK7lcfTuWknnfi6TDa8hTzZO3FkOIUgiRHsJwSC_1YRxpg8cmQiz-XLUKilhYoGu02SvAgoot9GBUlVPMNDUgwPnWr4VL9kpGsfDJpKV30pP-9sdujbgwOd1KsFdWtEJYV8nxre7Nq2c6udT0a9wrs_uD7ff1FfIfDAFJZqCJUgKMuQWjsy6fnTAbodvKprtnQDNjjO_0Q

### 根据 TableId 查询简单商品信息: 完整的 goods cache
### 第二步验证, 删掉 cache
### 第三步验证, 删除 cache 中其中一个商品
POST http://127.0.0.1:9001/asan/ecommerce-goods-service/goods/simple-goods-info
Content-Type: application/json
e-commerce-user: eyJhbGciOiJSUzI1NiJ9.eyJlLWNvbW1lcmNlLXVzZXIiOiJ7XCJpZFwiOjEwLFwidXNlcm5hbWVcIjpcImFzYW4xMjNAcXEuY29tXCJ9IiwianRpIjoiMjE1OTMwOTUtZTZhMi00Yzc3LWE5ZmItOGY1NTE3Y2M2MGI4IiwiZXhwIjoxNjQyODY3MjAwfQ.hdgjAjx-IVPDKdRUmz7oJJE7Wi1TizsPVJ_oyAPBYvp6DN7_oTRFzDDGGIUA3pbotLf5VUTpJ2XR7lkEmEx_8Yz-u8v5Q9DKSMt-avLwRGE5y3TLQmMx4RnKjq33Z6hTEshxuFzbRY1tXK7lcfTuWknnfi6TDa8hTzZO3FkOIUgiRHsJwSC_1YRxpg8cmQiz-XLUKilhYoGu02SvAgoot9GBUlVPMNDUgwPnWr4VL9kpGsfDJpKV30pP-9sdujbgwOd1KsFdWtEJYV8nxre7Nq2c6udT0a9wrs_uD7ff1FfIfDAFJZqCJUgKMuQWjsy6fnTAbodvKprtnQDNjjO_0Q

{
  "ids": [
    {
      "id": 10
    },
    {
      "id": 12
    }
  ]
}


### 扣减商品库存
PUT http://127.0.0.1:9001/asan/ecommerce-goods-service/goods/deduct-goods-inventory
Content-Type: application/json
e-commerce-user: eyJhbGciOiJSUzI1NiJ9.eyJlLWNvbW1lcmNlLXVzZXIiOiJ7XCJpZFwiOjEwLFwidXNlcm5hbWVcIjpcImFzYW4xMjNAcXEuY29tXCJ9IiwianRpIjoiMjE1OTMwOTUtZTZhMi00Yzc3LWE5ZmItOGY1NTE3Y2M2MGI4IiwiZXhwIjoxNjQyODY3MjAwfQ.hdgjAjx-IVPDKdRUmz7oJJE7Wi1TizsPVJ_oyAPBYvp6DN7_oTRFzDDGGIUA3pbotLf5VUTpJ2XR7lkEmEx_8Yz-u8v5Q9DKSMt-avLwRGE5y3TLQmMx4RnKjq33Z6hTEshxuFzbRY1tXK7lcfTuWknnfi6TDa8hTzZO3FkOIUgiRHsJwSC_1YRxpg8cmQiz-XLUKilhYoGu02SvAgoot9GBUlVPMNDUgwPnWr4VL9kpGsfDJpKV30pP-9sdujbgwOd1KsFdWtEJYV8nxre7Nq2c6udT0a9wrs_uD7ff1FfIfDAFJZqCJUgKMuQWjsy6fnTAbodvKprtnQDNjjO_0Q

[
  {
    "goodsId": 10,
    "count": 100
  },
  {
    "goodsId": 12,
    "count": 34
  }
]
